jayk-gupta/web-resources-project

src/components/books/CssB.jsx
Closes https://github.com/jayk-gupta/web-resources-project/issues/11
Removed the console.log from the CssB file
=> Removed console.log message from CssB file

.github/ISSUE_TEMPLATE/refactor_code.md
This template is used to identify and address issues in code that require refactoring. It helps in improving the codebase by reviewing and updating variable naming conventions, simplifying complex logic, optimizing performance, improving code readability and maintainability, enhancing error handling and validation, and updating comments and documentation as needed.
=> add Issue template for Refactor Code

.github/workflows/json-check.yml
add json checker gh action #84
=> ci: Create json-check.yml

.github/workflows/issue-lock.yml
=> ci: Create issue-lock.yml

src/App.jsx, src/components/websites/Websites.jsx
@jayk-gupta pls review my PR 
I had done the changes for website section.
=> showing resources of first category instead of showing "welcome to website section"

src/database/Tools/javascript.json
added Minify- JavaScript and CSS code minifier
closes #25 
added the resource
=> Added New Resource

public/Card Images/tools/tools.md
=> added Minify image

src/App.jsx, src/components/Welcome.jsx, src/components/books/Books.jsx, src/components/challenges/Challenges.jsx, src/components/tools/Tools.jsx, src/components/videos/Videos.jsx, src/components/websites/Websites.jsx
Closes issue UI Improvements #69
=> UI Improvements

public/Card Images/videos/videos.md, src/database/Videos/html.json
Adding video resource - Youtube Channel for HTML named developedbyed 
Closes: #61
=> Adding video resource - Youtube Channel

src/components/Card.jsx
Closes #118
Make the entire card clickable to provide a more intuitive user experience
=> Made the Whole Card Clickable

public/Card Images/website/website.md, src/database/Websites/javascript.json
This PR includes the addition of the Codecademy website as a resource in the JavaScript website section. Please review it. Thanks! @jayk-gupta
=> Add Resource in JavaScript Website Section

public/Card Images/challenges/challenges.md, src/database/Challenges/javascript.json
This PR includes the addition of the javascript30 website as a resource in the JavaScript challenge section. Please review it. Thanks! @jayk-gupta
=> Add Resource in JavaScript Challenge Section

CONTRIBUTING.md, src/components/Home.jsx
Updated the steps to push the changes to the repo
#164 
- Closes #[164]
- Added step to switch branch
- [Change 2]
- [Change 3]
[If there are any relevant screenshots, include them here.]
Please review and check the following before merging:
[Include any additional notes or considerations for the reviewers.]
=> [DOCS] Updated readme file

.github/workflows/add-contributors.js, .github/workflows/add-contributors.yml
Succesfully added two files in workflows folder for automatic addition of contributor name.
This closes issue #160
Please do check this once and kindly provide me with feedback :) @jayk-gupta 
Thank you 🙂
=> "Made changes for automatic addition of contributor name"

README.md
- I have added badges will will improve the look and also provide stats of the repo at the same time.
- I included a back-to-top link at the end of the ReadMe.md file for easier navigation.
- I have contributed under GSSoC'23.
=> Added badges and back-to-top link in ReadMe.md

src/database/books.json
Added few new books as a resource for css and  reactJs.
=> Added new Books

pnpm-lock.yaml, public/Card Images/website/website.md, src/database/websites.json
In the website section I have added some javascript website resource.
=> Added some Javascript Resoruce Website

src/database/videos.json
JavaScript video resource no. 8 - Code with Harry Playlist
the issue was #279 (which is now closed)
image file is already merged - #278
=> Added JavaScript Resource

src/database/videos.json
I have added the resources for react.js.
Please review it and If It is fine then please merge it to the main branch.
=> Added the resources for react.js by Parmesh Bhatt

src/database/videos.json
Closes issue #362 
I have added the resources of JavaScript. Please review it and If it is fine then please merge it to the main branch.
=> Added the video resources of clever programmer by Parmesh Bhatt

public/Card Images/website/website.md, src/database/websites.json
Added JavaScript Website resource and respective image complying the requirements specified.
=> JavaScript Resource

src/database/websites.json
In website section and then in reactjs section the image of javaTpoint was  not showing. So now I have added that image.
=> Bug:- images is not showing (in websites in reactjs for javatpoint)

package-lock.json, package.json, src/App.jsx, src/components/ScrollToTopButton.jsx
Added scroll to top button component
Issue Number - 430
closes #430 
Changes done
https://github.com/jayk-gupta/web-resources-project/assets/114330097/8f1853a2-5e39-4d60-aade-63fb6159fc96
=> [GSSoC'23] Scroll to Top Button Added

src/database/books.json
Added a HTML Book
Title - HTML5 notes for professionals
Issue Number - 428
closes #428
=> [GSSoC'23] Added HTML Book 

src/database/websites/javascript.json
Added JS learning websited
Issue Number - 452
close #452
=> [GSSoC'23] Added JS leaning websites 

src/components/books/Index.jsx, src/components/challenges/Index.jsx, src/components/tools/Index.jsx, src/components/videos/Index.jsx, src/components/websites/Index.jsx
Close issue #438 
Before the change of UI, there is an issue which I have posted. Now the issue was resolved after the improvement.
So I got a new observation of cards display on 14 inch laptop and made changes . If you think this changes are good then please accept it. 
Previous : 
https://github.com/jayk-gupta/web-resources-project/assets/88759473/ec2f0ef5-f059-4165-bcbd-14c2e81f847c
After Updating :
https://github.com/jayk-gupta/web-resources-project/assets/88759473/c46073e4-d90e-4180-872f-f217354b2fd2
=> Cards responsibility

package-lock.json, src/database/tools/css.json
=> css palette added

src/App.jsx
**Reduces initial load time** – Lazy loading a webpage reduces page weight, allowing for a quicker [page load time].
**Bandwidth conservation** – Lazy loading conserves bandwidth by delivering content to users only if it’s requested.
**System resource conservation** – Lazy loading conserves both server and client resources, because only some of the images, JavaScript, and other code actually need to be rendered or executed.
=> implement lazy loading

src/database/tools/css.json
=> color picker added

src/database/challenges/css.json, src/database/challenges/html.json
=> chore: add frontend practice challenge website for html and css ✨

src/database/challenges/css.json
I have added a new CSS Challenge in the challenge section .
Proof of Work is added below:
=> Css challenges 

src/components/Card.jsx, src/index.css
-Added hover animation on each cards images
https://github.com/jayk-gupta/web-resources-project/assets/101205226/269d6cfe-cf38-445d-ab31-f31a25c72e7a
=> Added animation on all cards images

src/components/nav/NavItem.jsx, src/components/nav/NavUI.jsx
=> bug-fix for activeTab issue #559

src/App.jsx, src/components/ScrollToTopButton.jsx
Closes #554 
Scroll to top button is added to each webpage.
**Screenshot:**
=> Added scroll to top to every page

src/database/challenges/css.json
Closes issue #569 
I have added a new Challenging CSS website
Proof of work: -
=> New CSS Resource

src/database/websites/reactjs.json
This pull request addresses and resolves an issue related to a React page on our website in the Websites category. The primary focus of this fix was to rectify a JSON error that was occurring within the ReactJS codebase.
Through a careful analysis of the issue, I identified and resolved the root cause of the JSON error, ensuring the React page now functions smoothly and as intended. The changes made in this pull request guarantee a seamless user experience, eliminating any disruptions caused by the JSON error.
```
{
"tag" : "html",
"title": "JavaTpoint",
"description": "ReactJS tutorial provides basic and advanced concepts of ReactJS. Currently, ReactJS is one of the most popular JavaScript front-end libraries which has a strong foundation and a large community.",
"link": …
```
=> Fixed React in website category

src/components/nav/SideNav.jsx, src/components/nav/SideNavMobile.jsx
bug fix for search issue #572  for mobile and web
mobile :- 
web :-
=> bug-fix-572 search issue

README.md
Closes issue #509 
I have updated Readme with every basic thing a contributor has to do before & while making a PR.
Proof of Work: -
=> [DOCS]: Update Readme

src/database/books/javascript.json, src/database/books/reactjs.json
=> books are added

src/database/tools/css.json
=> css animation added

src/database/websites/html.json, src/database/websites/javascript.json
close issue-> #585 
js of w3school
bud is resloved
=> wrong data deleted from website and java script tutorial is added[BUG is solved]

src/database/videos/reactjs.json
pls review, i have added this react js tut video
resolves issue #531
=> added react js video

src/database/websites/css.json, src/database/websites/html.json, src/database/websites/javascript.json, src/database/websites/reactjs.json, src/database/websites/tailwindcss.json
- Added DevDocs website Details in html.json, css.json, tailwindcss.json, reactjs.json and javascript.json Files.
- This Website is Very Helpful for Learning Web Development from Starting to Advanced Level.
=> feat: Added DevDocs.io website  Details in 5 Files in websites Category Section

src/index.css
I have successfully changed the layout of the scrollbar. Please see it and merge this PR under GSSOC'23. This PR is solving the issue [STYLE] Scroll bar is not Impressive #399
=> Improvised ScrollBar

src/components/books/Index.jsx, src/components/challenges/Index.jsx, src/components/nav/NavItem.jsx, src/components/nav/NavUI.jsx, src/components/nav/SideNav.jsx, src/components/tools/Index.jsx, src/components/videos/Index.jsx, src/components/websites/Index.jsx
Search Feature Added issue number #578
=> search Feature add  #578 

src/database/websites/tailwindcss.json
Fixes #583 
@jayk-gupta It's done
please check!
=> Image path and website link added

src/database/challenges/html.json
=> codewell added

src/components/filter/index.jsx
bug fix #608 
Tag Breaking in mobile
=> bug-fix #608 for mobile

src/database/challenges/css.json
closes issue #601 
I have added new challenge css resources to the website.
=> css resources added

src/database/challenges/javascript.json
=> js30 added

src/database/challenges/javascript.json
=> codewars added

src/database/challenges/javascript.json
=> dev challenges added
